services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ubereats
    volumes:
      - pgdata:/var/lib/postgresql/data
      # migration dir配下のファイルをcompose.ymlに登録することで、DB作成時（docker compose up -d）に毎回実行される
      # docker desktopのvolumeから削除するまでは、ホスト側にDBの情報が永続化されている
      - ./db/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata: